/**
 * Seed script: Create herbal_remedies table + insert 60+ Ayurvedic herbs
 * Run: node scripts/seed_herbal_remedies.mjs
 */
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://kpogtuutqaobnouhkvmt.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwb2d0dXV0cWFvYm5vdWhrdm10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDIzNDUsImV4cCI6MjA4NTg3ODM0NX0.PNUYRwfJxeq1KKA-2eUkDhcRgaJN8vDHYtvdaxJ3eI8';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// ======= TABLE CREATION SQL =======
const CREATE_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS herbal_remedies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  herb_name TEXT NOT NULL,
  benefits TEXT,
  preparation_method TEXT,
  dosage TEXT,
  precautions TEXT,
  related_symptoms TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE herbal_remedies ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'herbal_remedies' AND policyname = 'Public can view herbal remedies') THEN
    CREATE POLICY "Public can view herbal remedies" ON herbal_remedies FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'herbal_remedies' AND policyname = 'Public can insert herbal remedies') THEN
    CREATE POLICY "Public can insert herbal remedies" ON herbal_remedies FOR INSERT WITH CHECK (true);
  END IF;
END $$;
`;

// ======= 60+ AYURVEDIC HERBS DATA =======
const herbs = [
    { herb_name: "Ashwagandha", benefits: "Adaptogenic herb that reduces stress, boosts immunity, improves stamina, supports hormonal balance, and enhances cognitive function.", preparation_method: "Mix 1 tsp powder in warm milk or water. Can also be taken as capsules or decoction.", dosage: "300-600 mg standardized extract twice daily, or 1-2 tsp powder with warm milk before bed.", precautions: "Avoid during pregnancy. May interact with thyroid, blood sugar, and blood pressure medications. Not recommended in hyperthyroidism.", related_symptoms: ["stress", "fatigue", "anxiety", "insomnia", "low immunity", "weakness", "joint pain"] },
    { herb_name: "Brahmi", benefits: "Enhances memory, concentration, and cognitive function. Calms the mind, reduces anxiety, and supports nervous system health.", preparation_method: "Steep 1 tsp dried leaves in hot water for 10 minutes as tea. Also available as powder, capsules, or oil for scalp massage.", dosage: "300-450 mg extract daily, or 1 tsp powder with honey or ghee twice daily.", precautions: "May cause mild drowsiness. Avoid with sedative medications. Not recommended during pregnancy.", related_symptoms: ["anxiety", "stress", "poor memory", "insomnia", "mental fatigue", "concentration issues", "depression"] },
    { herb_name: "Tulsi (Holy Basil)", benefits: "Powerful adaptogen with antimicrobial, anti-inflammatory, and immunomodulatory properties. Supports respiratory and cardiovascular health.", preparation_method: "Brew 5-6 fresh leaves in boiling water for tulsi tea. Can also chew fresh leaves or take as capsules.", dosage: "300-600 mg extract daily, or 2-3 cups of tulsi tea per day.", precautions: "May lower blood sugar levels. Avoid in large amounts during pregnancy. May slow blood clotting.", related_symptoms: ["cold", "cough", "fever", "stress", "inflammation", "low immunity", "respiratory issues", "allergies"] },
    { herb_name: "Neem", benefits: "Potent blood purifier with antibacterial, antifungal, and antiviral properties. Excellent for skin health and detoxification.", preparation_method: "Boil neem leaves in water for a bitter decoction. Neem oil for topical application. Capsules for internal use.", dosage: "1-2 neem capsules (250-500 mg) daily, or neem tea once daily. Topical: apply neem paste or oil as needed.", precautions: "Extremely bitter taste. Avoid during pregnancy. Not for children under 2. May lower blood sugar excessively.", related_symptoms: ["skin problems", "acne", "infection", "blood impurities", "diabetes risk", "inflammation", "dental issues", "parasites"] },
    { herb_name: "Shatavari", benefits: "Premier female reproductive tonic. Supports fertility, lactation, hormonal balance, and digestive health. Also benefits male vitality.", preparation_method: "Mix 1 tsp powder in warm milk with honey. Available as capsules, tablets, or liquid extract.", dosage: "500-1000 mg twice daily, or 1/2-1 tsp powder with warm milk.", precautions: "Avoid if allergic to asparagus family. Use cautiously with hormone-sensitive conditions. May cause weight gain in Kapha types.", related_symptoms: ["hormonal imbalance", "infertility", "menstrual issues", "weakness", "acidity", "digestive issues", "low libido"] },
    { herb_name: "Triphala", benefits: "Gentle detoxifier and bowel regulator. Combines Amla, Haritaki, and Bibhitaki for complete digestive support and antioxidant benefits.", preparation_method: "Steep 1/2 tsp powder in warm water overnight, drink on empty stomach. Also available as tablets.", dosage: "500-1000 mg before bed or on empty stomach, or 1/2 tsp powder in warm water.", precautions: "May cause loose stools initially. Avoid during pregnancy. Not recommended with diarrhea.", related_symptoms: ["constipation", "digestive issues", "bloating", "detoxification", "weight management", "eye health", "acidity"] },
    { herb_name: "Amla (Indian Gooseberry)", benefits: "Richest natural source of Vitamin C. Powerful antioxidant, boosts immunity, supports digestion, improves skin and hair health.", preparation_method: "Eat fresh, as juice, or use dried powder in water. Amla murabbas (preserved in sugar) are popular.", dosage: "1-2 fresh amla daily, or 500-1000 mg amla powder, or 15-20 ml juice.", precautions: "May increase acidity in some people. Avoid with existing hyperacidity. May lower blood sugar.", related_symptoms: ["low immunity", "hair loss", "skin problems", "constipation", "acidity", "anemia", "vitamin deficiency", "cold"] },
    { herb_name: "Guduchi (Giloy)", benefits: "Powerful immunomodulator and anti-inflammatory. Excellent for fever management, liver protection, and chronic disease prevention.", preparation_method: "Boil fresh stem pieces in water. Also available as satva (starch), powder, tablets, or juice.", dosage: "500 mg powder twice daily, or 15-20 ml juice, or 1-2 tablets daily.", precautions: "May lower blood sugar excessively. Avoid auto-immune conditions. Consult before surgery.", related_symptoms: ["fever", "low immunity", "inflammation", "diabetes risk", "liver issues", "arthritis", "allergies", "chronic fatigue"] },
    { herb_name: "Arjuna", benefits: "Premier cardiac tonic in Ayurveda. Strengthens heart muscles, regulates blood pressure, reduces cholesterol, and improves circulation.", preparation_method: "Boil 1 tsp bark powder in milk to make ksheerpaka. Also available as capsules and tablets.", dosage: "500 mg twice daily with warm milk or water, or arjuna ksheerpaka once daily.", precautions: "May interact with cardiac medications. Monitor blood pressure. Avoid during pregnancy.", related_symptoms: ["high blood pressure", "high cholesterol", "heart weakness", "chest pain", "poor circulation", "edema", "fatigue"] },
    { herb_name: "Turmeric (Haridra)", benefits: "Powerful anti-inflammatory and antioxidant. Supports joint health, digestion, skin health, liver function, and immune response.", preparation_method: "Mix 1/2 tsp powder in warm milk (golden milk). Add black pepper for enhanced absorption. Use in cooking.", dosage: "500-1000 mg curcumin extract daily, or 1 tsp turmeric powder in warm milk with black pepper.", precautions: "May thin blood at high doses. Avoid with gallstones. May interact with blood thinners and diabetes medications.", related_symptoms: ["inflammation", "joint pain", "arthritis", "skin problems", "digestive issues", "cold", "low immunity", "wounds"] },
    { herb_name: "Licorice (Mulethi)", benefits: "Soothes respiratory tract, supports adrenal function, heals gastric ulcers, and acts as a natural expectorant and anti-inflammatory.", preparation_method: "Chew small pieces of root. Boil root in water for decoction. Powder can be mixed with honey.", dosage: "1-2 small root pieces to chew, or 200-400 mg extract daily, or decoction once daily.", precautions: "Avoid in hypertension. Long-term use may cause potassium depletion. Not for prolonged use beyond 4-6 weeks.", related_symptoms: ["cough", "sore throat", "acidity", "gastric ulcer", "respiratory issues", "adrenal fatigue", "inflammation"] },
    { herb_name: "Guggul", benefits: "Regulates lipid metabolism, reduces cholesterol, supports thyroid function, and has potent anti-inflammatory and detoxifying properties.", preparation_method: "Typically taken as purified guggul tablets or capsules (Kaishore Guggulu, Triphala Guggulu formulations).", dosage: "250-500 mg purified guggul extract 2-3 times daily after meals.", precautions: "May interact with thyroid medications and blood thinners. Avoid during pregnancy. May cause skin rashes.", related_symptoms: ["high cholesterol", "obesity", "thyroid issues", "arthritis", "inflammation", "joint pain", "skin problems"] },
    { herb_name: "Bhringraj", benefits: "Premier hair tonic in Ayurveda. Prevents hair loss, premature greying, and dandruff. Also supports liver health and calms the mind.", preparation_method: "Apply bhringraj oil to scalp for massage. Take powder with water or honey. Available as capsules.", dosage: "500 mg powder twice daily, or regular scalp massage with bhringraj oil 2-3 times per week.", precautions: "May cause drowsiness. Avoid excessive internal use during pregnancy. Patch test oil before use.", related_symptoms: ["hair loss", "premature greying", "dandruff", "insomnia", "liver issues", "stress", "headache", "skin problems"] },
    { herb_name: "Punarnava", benefits: "Excellent diuretic and kidney tonic. Reduces edema, supports urinary health, and rejuvenates the entire body.", preparation_method: "Boil root powder in water for decoction. Take as powder with warm water or as capsules.", dosage: "500-1000 mg powder twice daily, or punarnava decoction 30 ml twice daily.", precautions: "May cause excessive urination. Avoid with severe dehydration. Monitor electrolytes with long-term use.", related_symptoms: ["edema", "kidney issues", "urinary problems", "inflammation", "obesity", "anemia", "liver issues", "joint pain"] },
    { herb_name: "Shankhpushpi", benefits: "Brain tonic that enhances memory, intellect, and concentration. Calms the nervous system and promotes restful sleep.", preparation_method: "Brew dried herb as tea. Mix powder with milk or water. Available as syrup for children.", dosage: "250-500 mg extract twice daily, or 1-2 tsp powder with warm milk, or 2 tsp syrup.", precautions: "May increase drowsiness with sedative drugs. Avoid excessive doses during pregnancy.", related_symptoms: ["poor memory", "anxiety", "insomnia", "stress", "mental fatigue", "concentration issues", "epilepsy", "depression"] },
    { herb_name: "Moringa (Drumstick)", benefits: "Superfood rich in vitamins, minerals, and amino acids. Boosts energy, supports bone health, and provides complete nutrition.", preparation_method: "Add moringa powder to smoothies, soups, or warm water. Fresh leaves can be cooked as vegetables.", dosage: "1-2 tsp moringa powder daily in water or smoothie, or cook fresh leaves.", precautions: "Root and bark extracts should be avoided during pregnancy. May lower blood pressure and blood sugar.", related_symptoms: ["malnutrition", "fatigue", "anemia", "low immunity", "inflammation", "diabetes risk", "high blood pressure", "bone weakness"] },
    { herb_name: "Ginger (Shunti)", benefits: "Aids digestion, relieves nausea, reduces inflammation, improves circulation, and supports respiratory health.", preparation_method: "Grate fresh ginger into hot water for tea. Add to cooking. Dry ginger powder for medicinal use.", dosage: "1-2 cups ginger tea daily, or 250-500 mg dry ginger powder, or 1-inch fresh ginger.", precautions: "May aggravate Pitta. Avoid large doses with blood thinners. May worsen acid reflux in some.", related_symptoms: ["nausea", "digestive issues", "cold", "cough", "inflammation", "joint pain", "bloating", "poor circulation"] },
    { herb_name: "Cumin (Jeeraka)", benefits: "Enhances digestion, relieves bloating, improves iron absorption, and supports metabolism and weight management.", preparation_method: "Boil 1 tsp cumin seeds in water. Drink as cumin water (jeerakarishtam). Use in cooking.", dosage: "1-2 cups cumin water daily, or 1/2 tsp cumin powder with meals.", precautions: "Generally very safe. Excessive use may lower blood sugar. May increase bleeding during menstruation.", related_symptoms: ["bloating", "indigestion", "flatulence", "poor appetite", "weight management", "anemia", "diabetes risk"] },
    { herb_name: "Fennel (Saunf)", benefits: "Excellent digestive aid, reduces bloating and gas, freshens breath, supports eye health, and has mild estrogenic properties.", preparation_method: "Chew seeds after meals. Boil seeds in water for fennel tea. Add to cooking.", dosage: "1 tsp seeds after meals, or 1-2 cups fennel tea daily.", precautions: "May interact with estrogen-sensitive conditions. Avoid large medicinal doses during pregnancy.", related_symptoms: ["bloating", "gas", "indigestion", "bad breath", "eye strain", "menstrual cramps", "colic", "acidity"] },
    { herb_name: "Cardamom (Elaichi)", benefits: "Natural mouth freshener, digestive stimulant, detoxifier. Supports respiratory health and balances all three doshas.", preparation_method: "Chew pods after meals. Add powder to tea, milk, or desserts. Use in cooking.", dosage: "2-3 pods daily chewed or in tea, or 1/4 tsp powder.", precautions: "Generally very safe. May aggravate gallstone conditions. Avoid excessive amounts.", related_symptoms: ["bad breath", "indigestion", "nausea", "cough", "respiratory issues", "detoxification", "oral health"] },
    { herb_name: "Cinnamon (Dalchini)", benefits: "Regulates blood sugar, improves insulin sensitivity, has antimicrobial properties, and supports cardiovascular health.", preparation_method: "Add cinnamon stick to tea or warm water. Sprinkle powder on food. Cinnamon-honey combination.", dosage: "1/2-1 tsp powder daily in warm water or tea, or 1 cinnamon stick brewed.", precautions: "Ceylon cinnamon preferred over Cassia. Cassia contains coumarin which may harm liver in large doses. Avoid excessive use in pregnancy.", related_symptoms: ["diabetes risk", "high blood sugar", "cold", "poor circulation", "digestive issues", "infection", "inflammation"] },
    { herb_name: "Black Pepper (Maricha)", benefits: "Bioavailability enhancer for other herbs. Stimulates digestion, clears respiratory congestion, and has potent antioxidant properties.", preparation_method: "Add to food. Mix with honey for cough. Combine with turmeric for enhanced absorption.", dosage: "3-5 peppercorns daily, or 1/4 tsp powder with honey or in food.", precautions: "May aggravate Pitta. Avoid with gastric ulcers or hemorrhoids. Excessive use may irritate the stomach.", related_symptoms: ["cough", "congestion", "poor digestion", "poor absorption", "cold", "sinus issues", "obesity"] },
    { herb_name: "Aloe Vera (Kumari)", benefits: "Soothes skin, heals burns, supports digestion, detoxifies liver, and has mild laxative and anti-inflammatory properties.", preparation_method: "Extract fresh gel for topical use. Blend gel with water for juice. Available as capsules.", dosage: "15-30 ml aloe juice daily, or apply gel topically as needed. Capsules: 100-200 mg.", precautions: "Internal use may cause diarrhea. Avoid oral aloe latex during pregnancy. May lower blood sugar.", related_symptoms: ["skin problems", "burns", "constipation", "acidity", "inflammation", "wounds", "digestive issues", "hair loss"] },
    { herb_name: "Fenugreek (Methi)", benefits: "Regulates blood sugar, enhances lactation, reduces cholesterol, supports digestion, and has anti-inflammatory properties.", preparation_method: "Soak seeds overnight and eat in morning. Sprout seeds. Use powder in cooking or warm water.", dosage: "1-2 tsp soaked seeds daily, or 500-600 mg extract, or methi water on empty stomach.", precautions: "May lower blood sugar significantly. Avoid during pregnancy (may induce contractions). May cause maple-syrup-like body odor.", related_symptoms: ["diabetes risk", "high blood sugar", "high cholesterol", "inflammation", "digestive issues", "low lactation", "hair loss"] },
    { herb_name: "Ajwain (Carom Seeds)", benefits: "Powerful digestive aid, relieves gas and bloating, clears respiratory congestion, and has antimicrobial properties.", preparation_method: "Chew seeds with warm water. Boil in water for decoction. Add to cooking.", dosage: "1/2-1 tsp seeds with warm water after meals, or as decoction.", precautions: "May aggravate acidity in excess. Avoid large medicinal doses during pregnancy.", related_symptoms: ["gas", "bloating", "indigestion", "stomach pain", "cold", "cough", "acidity", "flatulence"] },
    { herb_name: "Triphala Guggulu", benefits: "Combined formulation for joint health, weight management, cholesterol reduction, and detoxification of deep tissues.", preparation_method: "Take as tablets with warm water after meals.", dosage: "2 tablets twice daily after meals with warm water.", precautions: "Avoid during pregnancy. May interact with cholesterol and thyroid medications. Start with lower dose.", related_symptoms: ["joint pain", "arthritis", "obesity", "high cholesterol", "inflammation", "skin problems", "fistula"] },
    { herb_name: "Kutki", benefits: "Premier liver-protective herb. Supports bile production, detoxifies liver, and has anti-inflammatory and immune-modulating properties.", preparation_method: "Take powder with warm water or honey. Available as churna or tablets.", dosage: "125-250 mg powder twice daily with warm water or honey.", precautions: "Avoid during pregnancy. May cause slight nausea initially. Not for long-term use without supervision.", related_symptoms: ["liver issues", "jaundice", "hepatitis", "skin problems", "fever", "inflammation", "digestive issues"] },
    { herb_name: "Vidanga", benefits: "Potent anti-parasitic herb. Supports digestive health, reduces flatulence, and aids in weight management.", preparation_method: "Take powder with honey or warm water. Available as tablets.", dosage: "500-1000 mg powder daily with honey or warm water.", precautions: "Avoid during pregnancy and breastfeeding. Not for children without practitioner guidance.", related_symptoms: ["parasites", "worms", "flatulence", "obesity", "digestive issues", "skin problems", "bloating"] },
    { herb_name: "Vacha (Sweet Flag)", benefits: "Enhances speech, memory, and intellect. Supports respiratory health and aids in clearing mental fog.", preparation_method: "Very small amounts of powder with honey. Root decoction for gargling.", dosage: "125-250 mg powder with honey once daily, or decoction for gargling.", precautions: "Use only in small amounts. Avoid during pregnancy. Some varieties contain beta-asarone — use only Acorus calamus.", related_symptoms: ["speech issues", "poor memory", "mental fog", "sore throat", "epilepsy", "anxiety", "respiratory issues"] },
    { herb_name: "Haritaki (Chebulic Myrobalan)", benefits: "Part of Triphala. Gentle laxative, supports all tissues, enhances intelligence, and is called the 'King of Medicines' in Ayurveda.", preparation_method: "Take powder with warm water, honey, or ghee depending on desired effect.", dosage: "500 mg-1g powder at bedtime with warm water, or as directed.", precautions: "Avoid during pregnancy and extreme debility. May cause loose stools initially.", related_symptoms: ["constipation", "digestive issues", "eye health", "cognitive decline", "cough", "skin problems", "detoxification"] },
    { herb_name: "Bibhitaki (Baheda)", benefits: "Part of Triphala. Excellent for respiratory health, eye health, and hair growth. Reduces Kapha-related disorders.", preparation_method: "Take powder with honey for respiratory issues. Mixed in Triphala formulation.", dosage: "500 mg-1g powder with honey or warm water daily.", precautions: "Avoid during pregnancy. May cause dryness if used alone for extended periods.", related_symptoms: ["cough", "respiratory issues", "hair loss", "eye problems", "sore throat", "hoarseness", "digestive issues"] },
    { herb_name: "Manjistha", benefits: "Premier blood purifier in Ayurveda. Clears skin conditions, supports lymphatic drainage, and has anti-inflammatory properties.", preparation_method: "Take powder with warm water or milk. Manjistha paste for topical application on skin.", dosage: "500 mg-1g powder twice daily with warm water, or as prescribed.", precautions: "May increase menstrual flow. Avoid during pregnancy. Stains clothing and surfaces red.", related_symptoms: ["skin problems", "acne", "eczema", "blood impurities", "inflammation", "pigmentation", "lymphatic congestion"] },
    { herb_name: "Gokshura (Tribulus)", benefits: "Supports kidney and urinary tract health, enhances vitality and stamina, and promotes healthy reproductive function in both men and women.", preparation_method: "Decoction of fruit or powder with warm water or milk.", dosage: "500 mg-1g powder twice daily with warm water or milk.", precautions: "May interact with diabetes and blood pressure medications. Avoid during pregnancy.", related_symptoms: ["urinary problems", "kidney stones", "low stamina", "low libido", "infertility", "edema", "prostate issues"] },
    { herb_name: "Bala", benefits: "Strengthening herb that builds muscle mass, improves nerve function, and acts as a general body tonic.", preparation_method: "Decoction with milk. Oil for external massage (Bala Taila).", dosage: "500 mg-1g powder with warm milk twice daily. External: massage oil as needed.", precautions: "Avoid in conditions of congestion or excessive Kapha. Consult practitioner for dosage.", related_symptoms: ["weakness", "muscle wasting", "nerve pain", "fatigue", "paralysis", "low stamina", "joint pain"] },
    { herb_name: "Sarpagandha (Indian Snakeroot)", benefits: "Traditional herb for managing high blood pressure and calming the nervous system.", preparation_method: "Strictly as tablets or capsules under medical supervision only.", dosage: "ONLY under practitioner guidance — typical 50-100 mg of standardized extract.", precautions: "MUST be used under medical supervision. Can cause severe hypotension, depression, and sedation. Contraindicated in depression and peptic ulcers.", related_symptoms: ["high blood pressure", "insomnia", "anxiety", "mental agitation", "hypertension"] },
    { herb_name: "Yashtimadhu (Licorice Root)", benefits: "Soothes gastric inflammation, supports respiratory health, and acts as a natural sweetener and flavoring agent.", preparation_method: "Chew root pieces. Add to herbal tea blends. Powder with honey for cough.", dosage: "1-3g root daily, or 200-400 mg extract. Use for 4-6 weeks at a time.", precautions: "Contraindicated in hypertension and hypokalemia. Avoid prolonged use. Not for kidney disease patients.", related_symptoms: ["sore throat", "cough", "acidity", "gastric ulcer", "inflammation", "voice hoarseness", "adrenal fatigue"] },
    { herb_name: "Jatamansi", benefits: "Powerful nervine tonic that calms the mind, promotes sleep, and supports emotional balance. Used in treating neurological disorders.", preparation_method: "Take powder with warm milk at bedtime. Available as oil for head massage.", dosage: "250-500 mg powder at bedtime with warm milk. Oil: apply to scalp and temples.", precautions: "May cause drowsiness. Avoid operating machinery after intake. Not for use during pregnancy.", related_symptoms: ["insomnia", "anxiety", "stress", "epilepsy", "depression", "mental agitation", "headache", "hair loss"] },
    { herb_name: "Chitrak", benefits: "Powerful digestive fire stimulant. Enhances metabolism, reduces abdominal fat, and supports thyroid function.", preparation_method: "Take root powder with warm water or buttermilk.", dosage: "250-500 mg powder with warm water or buttermilk after meals.", precautions: "Strong herb — use in small doses. Avoid during pregnancy. May irritate gastric lining if taken in excess.", related_symptoms: ["poor digestion", "obesity", "thyroid issues", "bloating", "loss of appetite", "sluggish metabolism"] },
    { herb_name: "Shilajit", benefits: "Mineral-rich rejuvenator that enhances energy, stamina, and cognitive function. Supports healthy aging and reproductive health.", preparation_method: "Dissolve pea-sized amount in warm milk or water. Available as capsules.", dosage: "250-500 mg purified shilajit daily in warm milk, or 1-2 capsules daily.", precautions: "Use only purified shilajit. Avoid with gout or high uric acid. Not for children.", related_symptoms: ["fatigue", "weakness", "aging", "low stamina", "cognitive decline", "diabetes risk", "anemia", "low libido"] },
    { herb_name: "Tagar (Indian Valerian)", benefits: "Natural sedative and sleep aid. Calms anxiety, reduces muscle tension, and supports nervous system health.", preparation_method: "Take powder with warm milk at bedtime. Available as tablets or capsules.", dosage: "250-500 mg powder or 1-2 tablets at bedtime.", precautions: "May cause excessive drowsiness. Do not combine with other sedatives. Avoid driving after taking.", related_symptoms: ["insomnia", "anxiety", "muscle tension", "restlessness", "stress", "nerve pain", "headache"] },
    { herb_name: "Pippali (Long Pepper)", benefits: "Rejuvenates respiratory system, enhances bioavailability of medicines, stimulates digestion, and strengthens immunity.", preparation_method: "Take powder with honey. Add to food. Pippali rasayana preparation with ghee and honey.", dosage: "250-500 mg powder with honey, or 1-2 pippali fruits daily.", precautions: "May aggravate Pitta. Avoid with gastric ulcers. Traditional use involves graduated dosing (vardhamana).", related_symptoms: ["cough", "asthma", "respiratory issues", "poor digestion", "cold", "low immunity", "congestion"] },
    { herb_name: "Amalaki Rasayana", benefits: "Anti-aging formulation based on Amla. Promotes longevity, strengthens all tissues, and provides comprehensive antioxidant support.", preparation_method: "Take as churna (powder) with honey and ghee, or as tablets.", dosage: "1-2 tsp powder with honey and ghee, or 2 tablets twice daily.", precautions: "Avoid with existing hyperacidity. Diabetics monitor blood sugar.", related_symptoms: ["aging", "low immunity", "vitamin deficiency", "fatigue", "hair loss", "skin problems", "weakness"] },
    { herb_name: "Kanchanar (Bauhinia)", benefits: "Primary herb for thyroid disorders and lymphatic system. Reduces swelling, supports glandular health, and manages growths.", preparation_method: "Bark decoction. Kanchanar Guggulu tablets are the classical formulation.", dosage: "Kanchanar Guggulu: 2 tablets twice daily. Bark decoction: 20-30 ml twice daily.", precautions: "Avoid during pregnancy. Consult practitioner for thyroid conditions. Long-term use needs supervision.", related_symptoms: ["thyroid issues", "swollen glands", "cysts", "tumors", "obesity", "skin growths", "lymphatic congestion"] },
    { herb_name: "Dashamoola", benefits: "Combination of ten roots with powerful anti-inflammatory, analgesic, and muscle-relaxant properties. Balances Vata dosha.", preparation_method: "Decoction of the ten root powders. Available as tablets, kashayam, or oil for external use.", dosage: "15-20 ml decoction twice daily, or 2 tablets twice daily.", precautions: "Avoid during pregnancy. Some formulations are strong — consult practitioner.", related_symptoms: ["joint pain", "back pain", "inflammation", "muscle pain", "nerve pain", "postpartum health", "respiratory issues"] },
    { herb_name: "Sariva (Indian Sarsaparilla)", benefits: "Blood purifier with cooling properties. Supports skin health, urinary health, and helps manage Pitta-related disorders.", preparation_method: "Decoction of root. Sariva syrup mixed with water. Available as powder.", dosage: "500 mg-1g powder with water twice daily, or 15-20 ml syrup with water.", precautions: "Generally very safe. Excessive use may increase Kapha. Avoid large doses during pregnancy.", related_symptoms: ["skin problems", "urinary issues", "blood impurities", "burning sensation", "acne", "inflammation", "heat-related conditions"] },
    { herb_name: "Musta (Nagarmotha)", benefits: "Excellent digestive herb. Reduces diarrhea, supports gut health, has anti-inflammatory and analgesic properties.", preparation_method: "Decoction of tuber. Powder mixed with warm water or honey.", dosage: "500 mg-1g powder with warm water or honey twice daily.", precautions: "May reduce breast milk production. Avoid during breastfeeding in large doses.", related_symptoms: ["diarrhea", "digestive issues", "fever", "inflammation", "menstrual cramps", "skin problems", "worm infestation"] },
    { herb_name: "Nirgundi (Vitex)", benefits: "Potent pain reliever and anti-inflammatory. Supports joint health, respiratory health, and wound healing.", preparation_method: "Leaf decoction for internal use. Oil prepared from leaves for topical application on joints.", dosage: "15-20 ml leaf decoction daily. Topical: oil massage on affected joints.", precautions: "Avoid during pregnancy. May interact with hormonal medications.", related_symptoms: ["joint pain", "arthritis", "headache", "inflammation", "respiratory issues", "wounds", "sprains", "muscle pain"] },
    { herb_name: "Aswagandharishta", benefits: "Classical Ayurvedic fermented formulation of Ashwagandha. Enhanced bioavailability. Strengthens body, improves sleep and appetite.", preparation_method: "Dilute 15-25 ml with equal amount of warm water. Take after meals.", dosage: "15-25 ml with equal water, twice daily after meals.", precautions: "Contains self-generated alcohol (5-10%). Avoid if alcohol-sensitive. Not during pregnancy.", related_symptoms: ["fatigue", "weakness", "insomnia", "poor appetite", "anxiety", "stress", "low immunity", "debility"] },
    { herb_name: "Kumkumadi Tailam", benefits: "Luxurious facial oil that improves skin complexion, reduces blemishes, fights acne, and provides natural skin radiance.", preparation_method: "Apply 3-4 drops to clean face and massage gently. Use at night before bed.", dosage: "External use only: 3-4 drops on face nightly. Massage for 5 minutes.", precautions: "External use only. Patch test first. Some formulations contain saffron — verify ingredients for allergies.", related_symptoms: ["skin problems", "acne", "dark spots", "pigmentation", "dull skin", "wrinkles", "uneven skin tone"] },
    { herb_name: "Sunthi (Dry Ginger)", benefits: "Warming digestive aid distinct from fresh ginger. Reduces Vata and Kapha, supports respiratory health and joint mobility.", preparation_method: "Mix powder with warm water and honey. Add to tea. Sunthi-jaggery balls for cough.", dosage: "500 mg-1g powder with warm water and honey, twice daily.", precautions: "May aggravate Pitta. Avoid with bleeding disorders and gastric ulcers.", related_symptoms: ["cold", "cough", "indigestion", "joint pain", "congestion", "nausea", "bloating", "poor appetite"] },
    { herb_name: "Daruharidra (Tree Turmeric)", benefits: "Natural antibiotic with liver-protective properties. Excellent for skin and eye infections.", preparation_method: "Decoction for internal use. Paste for topical application. Eye wash preparation.", dosage: "500 mg-1g powder twice daily, or decoction 15-20 ml.", precautions: "May lower blood sugar. Avoid during pregnancy. Use eye preparations only under practitioner guidance.", related_symptoms: ["skin infection", "eye problems", "diabetes risk", "liver issues", "wound healing", "diarrhea", "inflammation"] },
    { herb_name: "Lodhra", benefits: "Astringent herb excellent for managing abnormal uterine bleeding, skin conditions, and dental health.", preparation_method: "Powder with water or rice wash water. Paste for topical facial application.", dosage: "500 mg-1g powder twice daily with water.", precautions: "Avoid during pregnancy. May cause constipation if used in excess.", related_symptoms: ["menstrual issues", "heavy bleeding", "skin problems", "acne", "dental issues", "diarrhea", "leucorrhea"] },
    { herb_name: "Kapikacchu (Mucuna)", benefits: "Natural source of L-DOPA. Supports neurological health, enhances mood, improves fertility, and builds muscle strength.", preparation_method: "Powder with warm milk. Available as capsules.", dosage: "500 mg-1g powder with warm milk, twice daily.", precautions: "May interact with medications for Parkinson's, depression, and psychosis. Avoid with melanoma.", related_symptoms: ["depression", "low libido", "infertility", "weakness", "nerve disorders", "stress", "tremors", "low stamina"] },
    { herb_name: "Rasna", benefits: "Effective anti-rheumatic herb. Manages joint pain, reduces inflammation, and supports respiratory health.", preparation_method: "Decoction of root. Rasnadi formulations. Also available as powder.", dosage: "500 mg-1g powder twice daily, or 15-20 ml decoction.", precautions: "Generally safe. Avoid during pregnancy. Consult practitioner for dosage.", related_symptoms: ["joint pain", "arthritis", "sciatica", "back pain", "respiratory issues", "inflammation", "asthma"] },
    { herb_name: "Eranda (Castor)", benefits: "Gentle purgative for deep cleansing. Castor oil supports joint health, relieves constipation, and promotes detoxification.", preparation_method: "Castor oil massage for joints. Internal use: 1-2 tsp oil with warm milk for purgation.", dosage: "External: massage oil as needed. Internal purgation: 15-30 ml castor oil (under guidance only).", precautions: "Internal purgation ONLY under practitioner guidance. Avoid during pregnancy. May cause severe cramping if overused.", related_symptoms: ["constipation", "joint pain", "arthritis", "detoxification", "skin problems", "bloating", "worm infestation"] },
    { herb_name: "Trikatu", benefits: "Combination of ginger, black pepper, and pippali. Powerful digestive stimulant, metabolism booster, and respiratory decongestant.", preparation_method: "Take powder with honey before meals. Available as tablets.", dosage: "250-500 mg powder with honey before meals, or 1-2 tablets.", precautions: "May aggravate Pitta and acidity. Avoid with gastric ulcers. Not during pregnancy.", related_symptoms: ["poor digestion", "obesity", "cold", "congestion", "sluggish metabolism", "low appetite", "sinus issues", "cough"] },
    { herb_name: "Amlaki (Amla Churna)", benefits: "Vitamin C powerhouse in powdered form. Supports immunity, improves digestion, and rejuvenates all body tissues.", preparation_method: "Mix powder with water, honey, or in smoothies. Can be taken with ghee.", dosage: "1-2 tsp powder daily with warm water or honey.", precautions: "May increase acidity initially. Diabetics should monitor blood sugar.", related_symptoms: ["vitamin deficiency", "low immunity", "hair loss", "fatigue", "digestive issues", "anemia", "premature aging"] },
    { herb_name: "Kalmegh (Andrographis)", benefits: "Powerful bitter herb that supports liver, boosts immunity, fights infections, and manages fever.", preparation_method: "Take powder or tablets with warm water. Extremely bitter.", dosage: "500 mg-1g powder or 1-2 tablets twice daily with warm water.", precautions: "Very bitter. May cause nausea. Avoid during pregnancy. May lower blood pressure.", related_symptoms: ["fever", "infection", "liver issues", "low immunity", "cold", "cough", "inflammation", "diabetes risk"] },
    { herb_name: "Saffron (Kesar)", benefits: "Mood enhancer, complexion improver, and cognitive support. Rich in antioxidants with anti-depressant properties.", preparation_method: "Soak 2-3 strands in warm milk. Add to food and desserts.", dosage: "2-4 strands (20-30 mg) daily in warm milk. Do not exceed 1.5g/day.", precautions: "Expensive; beware of adulteration. Excessive amounts may be toxic. Avoid large doses during pregnancy.", related_symptoms: ["depression", "dull skin", "memory issues", "menstrual cramps", "insomnia", "stress", "poor complexion"] },
    { herb_name: "Bakuchi (Psoralea)", benefits: "Primary herb for vitiligo and skin depigmentation disorders. Supports skin pigmentation and has photosensitizing properties.", preparation_method: "Seed powder taken internally. Oil for topical application on depigmented skin patches.", dosage: "250-500 mg powder daily. Topical: apply oil to affected skin with supervised sun exposure.", precautions: "Causes photosensitivity — avoid excessive sun exposure after application. Not during pregnancy. Liver function monitoring needed.", related_symptoms: ["vitiligo", "skin depigmentation", "psoriasis", "skin problems", "leucoderma"] },
    { herb_name: "Nagkesar", benefits: "Reduces bleeding disorders, supports skin health, and has anti-inflammatory and antimicrobial properties.", preparation_method: "Powder mixed with honey or warm water. Applied as paste for skin.", dosage: "250-500 mg powder with honey twice daily.", precautions: "Avoid in excess during pregnancy. May cause constipation.", related_symptoms: ["bleeding disorders", "skin problems", "piles", "heavy menstruation", "cough", "acne", "wounds"] },
    { herb_name: "Kantakari (Yellow Nightshade)", benefits: "Excellent respiratory herb for asthma, cough, and bronchitis. Has expectorant and bronchodilator properties.", preparation_method: "Decoction of root and fruit. Powder with honey for cough.", dosage: "500 mg-1g powder with honey, or 15-20 ml decoction twice daily.", precautions: "Fruit contains alkaloids — use only under guidance. Avoid during pregnancy.", related_symptoms: ["asthma", "cough", "bronchitis", "respiratory issues", "sore throat", "fever", "worm infestation"] },
];

// ======= MAIN EXECUTION =======
async function main() {
    console.log('=== AyurWell Herbal Remedies Seed Script ===\n');

    // Step 1: Try to create the table via SQL
    console.log('[1/3] Attempting to create herbal_remedies table...');
    console.log('      (If table creation fails, please run the SQL below in your Supabase SQL Editor)');
    console.log('─'.repeat(60));

    // Try to check if table exists by querying it
    const { data: checkData, error: checkError } = await supabase
        .from('herbal_remedies')
        .select('id')
        .limit(1);

    if (checkError && checkError.message.includes('does not exist')) {
        console.log('\n⚠️  Table does not exist. Please create it by running this SQL in your Supabase SQL Editor:');
        console.log('    (Go to: https://supabase.com/dashboard → Your Project → SQL Editor)\n');
        console.log(CREATE_TABLE_SQL);
        console.log('\n─'.repeat(60));
        console.log('After creating the table, re-run this script: node scripts/seed_herbal_remedies.mjs');
        process.exit(1);
    } else if (checkError) {
        console.log(`⚠️  Unexpected error: ${checkError.message}`);
        console.log('   Table may not exist. Please create it using the SQL above.');
        console.log('\n   Attempting to insert anyway...\n');
    } else {
        console.log('✅ Table herbal_remedies exists!');
        if (checkData && checkData.length > 0) {
            // Check how many records exist
            const { count } = await supabase.from('herbal_remedies').select('*', { count: 'exact', head: true });
            console.log(`   Current records: ${count || 'unknown'}`);
        }
    }

    // Step 2: Clear existing data (optional)
    console.log('\n[2/3] Clearing existing data...');
    const { error: deleteError } = await supabase.from('herbal_remedies').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    if (deleteError) {
        console.log(`   Note: Could not clear existing data (${deleteError.message}). Inserting anyway.`);
    } else {
        console.log('   ✅ Cleared existing data.');
    }

    // Step 3: Insert herbs in batches
    console.log(`\n[3/3] Inserting ${herbs.length} herbal remedies...`);
    const BATCH_SIZE = 15;
    let inserted = 0;
    let errors = 0;

    for (let i = 0; i < herbs.length; i += BATCH_SIZE) {
        const batch = herbs.slice(i, i + BATCH_SIZE);
        const { data, error } = await supabase.from('herbal_remedies').insert(batch).select('id');

        if (error) {
            console.log(`   ❌ Batch ${Math.floor(i / BATCH_SIZE) + 1} failed: ${error.message}`);
            errors++;
        } else {
            inserted += data.length;
            console.log(`   ✅ Batch ${Math.floor(i / BATCH_SIZE) + 1}: inserted ${data.length} herbs (total: ${inserted})`);
        }
    }

    console.log(`\n${'═'.repeat(60)}`);
    console.log(`✅ Done! Inserted ${inserted} herbal remedies.`);
    if (errors > 0) console.log(`⚠️  ${errors} batches had errors.`);
    console.log(`\nVerify at: ${SUPABASE_URL}/rest/v1/herbal_remedies?select=herb_name&limit=5`);
    console.log('Or open the Herbal Remedies page in your app!');
}

main().catch(err => { console.error('Fatal error:', err); process.exit(1); });
